# Dosya adı: sota_grouping_config.yaml
#

hardware:
  detection: "hardware_info"  # hardware_info.md konumuna göre otomatik belirleme (varsayılan)
  # detection: "path_index"    # Yolun belirli konumuna göre gruplama
  # detection: "manual"        # El ile eşleme
  
  # path_index modu için
  path_index: 2  # Flow/TypeII/XXX yolunda XXX kısmı (0'dan sayılır)
  
  manual_groups:
    - name: "single-node"
      patterns: ["single-node", "1node", "single"]
    - name: "multi-node"
      patterns: ["multi-node", "multi", "distributed"]
    - name: "gpu-cluster"
      patterns: ["gpu", "cuda-cluster", "multi-gpu"]

family:
  separator: "_"  # OpenMP_MPI gibi biçim (varsayılan)
  
  generation_rules:
    - generation: 1
      separator_count: 0  # OpenMP, MPI, CUDA
    - generation: 2
      separator_count: 1  # OpenMP_MPI, MPI_CUDA
    - generation: 3
      separator_count: 2  # OpenMP_MPI_AVX2
  
  explicit_relationships:
    OpenMP_MPI:
      parents: [OpenMP, MPI]
      generation: 2
    OpenMP_MPI_AVX2:
      parents: [OpenMP_MPI, AVX2]
      generation: 3

visualization:
  milestones: [30, 60, 90, 120, 180]
  
  style:
    line_width: 2.5
    marker_size: 6
    sota_line_style: "--"
    sota_line_alpha: 0.5
  
  output:
    dpi: 120
    format: "png"
    save_milestones: true  # Dönüm noktasında ayrı bir dizine kaydet
